// <auto-generated />
using System;
using System.Text.Json;
using AnalyticsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnalyticsService.Migrations
{
    [DbContext(typeof(HealthContext))]
    [Migration("20251121053449_CreateDailySummariesTableFinal")]
    partial class CreateDailySummariesTableFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalyticsService.Models.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgHeartRate")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_heart_rate");

                    b.Property<DateTime>("CalculationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculation_time");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("summary_date");

                    b.Property<double>("TotalSleepHours")
                        .HasColumnType("double precision")
                        .HasColumnName("total_sleep_hours");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("integer")
                        .HasColumnName("total_steps");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("daily_summaries");
                });

            modelBuilder.Entity("AnalyticsService.Models.RawDataRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonDocument>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime>("IngestionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("raw_health_data", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
