// <auto-generated />
using AnalyticsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyticsService.Migrations.ProcessingStatus
{
    [DbContext(typeof(ProcessingStatusContext))]
    [Migration("20251129043745_InitialProcessingStatus")]
    partial class InitialProcessingStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AnalyticsService.Data.Models.ProcessingStatus", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("ProcessingStatuses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
